#pragma once

namespace astra::ast {
enum class NodeKind {
    Program,
    TopLevelObject,
    FunctionDecl,
    VarDecl,
    Parameter,
    TypeRef,
    BuiltinType,
    ArrayType,
    FunctionType,
    Block,
    DeclStatement,
    ExprStmt,
    AssignmentStmt,
    IfStmt,
    ForStmt,
    ForEachStmt,
    WhileStmt,
    DoWhileStmt,
    NullLiteral,
    BoolLiteral,
    IntLiteral,
    FloatLiteral,
    VarExpr,
    UnaryExpr,
    BinaryExpr,
    IfExpr,
    ThrowExpr,
    ReturnExpr,
    ContinueExpr,
    BreakExpr,
    CallExpr,
    IndexExpr,
    MemberExpr,
    IsExpr,
    AsExpr,
    ThisExpr,
    CollectionExpr,
    Label,
};
} // namespace astra::ast